app:
  name: "web_app"
  mode: "dev"
  port: 18081
  ID: 1
  start_time: "2025-03-25"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "12345"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 20

redis:
  host: "127.0.0.1"
  port: 32768
  db: 0
  password: ""
  pool_size: 100


kafka:
  brokers:
    - "127.0.0.1:29092"
  producer:
    return_successes: true
  consumer: {}

jwt_secret: "kklluu"